from typing import Protocol, List, Optional, Dict, Any
from app.schemas.invoice import Invoice, SendEmailRequest
from app.schemas.results import (
    InvoiceResult,
    DownloadResult,
    InvoiceDataResult,
    DeleteInvoiceResult,
    InvoiceEventsResult,
)
from app.schemas.auth_token import AuthToken


class AuthService(Protocol):
    async def authenticate(self, email: str, password: str) -> AuthToken: ...
    async def refresh_token(self, refresh_token: str) -> AuthToken: ...


class InvoiceService(Protocol):
    async def create_invoice(self, invoice: Invoice, token: str) -> InvoiceResult: ...
    async def download_pdf(self, number: str, token: str) -> DownloadResult: ...
    async def download_xml(self, number: str, token: str) -> DownloadResult: ...
    async def get_invoice(self, number: str, token: str) -> InvoiceDataResult: ...
    async def delete_invoice(
        self, reference_code: str, token: str
    ) -> DeleteInvoiceResult: ...
    async def send_email(
        self, number: str, request: SendEmailRequest, token: str
    ) -> None: ...
    async def get_invoice_events(
        self, number: str, token: str
    ) -> InvoiceEventsResult: ...


class LookupService(Protocol):
    async def get_municipalities(self, token: str) -> List[Any]: ...
    async def get_tax_types(self, token: str) -> List[Any]: ...
    async def get_units(self, token: str) -> List[Any]: ...
    async def get_countries(
        self, token: str, name: Optional[str] = None
    ) -> List[Any]: ...
    async def get_acquirer(
        self, token: str, identification_document_type: str, identification_number: str
    ) -> Any: ...


class NumberingRangeService(Protocol):
    async def get_numbering_ranges(
        self, token: str, filters: Optional[Dict[str, Any]] = None
    ) -> Any: ...
    async def get_numbering_range(self, range_id: int, token: str) -> Any: ...
    async def create_numbering_range(self, data: Any, token: str) -> Any: ...
    async def update_numbering_range_consecutive(
        self, range_id: int, data: Any, token: str
    ) -> Any: ...
    async def delete_numbering_range(self, range_id: int, token: str) -> Any: ...
    async def get_software_numbering_ranges(self, token: str) -> Any: ...


class CompanyService(Protocol):
    async def get_company(self, token: str) -> Any: ...
    async def update_company(self, company: Any, token: str) -> Any: ...
    async def update_company_logo(
        self, file_name: str, file_content: bytes, file_content_type: str, token: str
    ) -> Any: ...
