
services:
  factus-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: factus-api
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - shared-backend-net

networks:
  shared-backend-net:
    external: true
    name: baiji-backend_backend-prod
